import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeEmpty : Empty, Equatable {
    init() {
    }

    static func reset() {
    }
}

func == (a: FakeEmpty, b: FakeEmpty) -> Bool {
    return a === b
}